/**
 * Built-in Models.dev Data
 *
 * Static snapshot of models.dev API data for offline use.
 * This serves as the primary data source, with network fetch as optional refresh.
 *
 * Last updated: 2026-02-26
 * Source: https://models.dev/api.json
 */

import type { ModelsDevRawProvider } from '../types/models-dev.js';

/**
 * Built-in providers data
 * Contains major providers with their models
 */
export const BUILT_IN_PROVIDERS: ModelsDevRawProvider[] = [
  {
    id: 'openai',
    name: 'OpenAI',
    api: 'https://api.openai.com/v1',
    npm: 'openai',
    doc: 'https://platform.openai.com/docs',
    env: ['OPENAI_API_KEY'],
    models: {
      'gpt-4o': {
        id: 'gpt-4o',
        name: 'GPT-4o',
        family: 'gpt-4o',
        reasoning: false,
        tool_call: true,
        temperature: true,
        attachment: true,
        modalities: { input: ['text', 'image'], output: ['text'] },
        limit: { context: 128000, output: 16384 },
        cost: { input: 2.5, output: 10.0 },
        knowledge: '2023-10',
        release_date: '2024-05-13',
        last_updated: '2024-05-13',
        open_weights: false,
      },
      'gpt-4o-mini': {
        id: 'gpt-4o-mini',
        name: 'GPT-4o Mini',
        family: 'gpt-4o',
        reasoning: false,
        tool_call: true,
        temperature: true,
        attachment: true,
        modalities: { input: ['text', 'image'], output: ['text'] },
        limit: { context: 128000, output: 16384 },
        cost: { input: 0.15, output: 0.6 },
        knowledge: '2023-10',
        release_date: '2024-07-18',
        last_updated: '2024-07-18',
        open_weights: false,
      },
      'o3-mini': {
        id: 'o3-mini',
        name: 'o3 Mini',
        family: 'o3',
        reasoning: true,
        tool_call: true,
        temperature: false,
        attachment: true,
        modalities: { input: ['text'], output: ['text'] },
        limit: { context: 200000, output: 100000 },
        cost: { input: 1.1, output: 4.4 },
        knowledge: '2023-10',
        release_date: '2025-01-31',
        last_updated: '2025-01-31',
        open_weights: false,
      },
      'o1': {
        id: 'o1',
        name: 'o1',
        family: 'o1',
        reasoning: true,
        tool_call: true,
        temperature: false,
        attachment: true,
        modalities: { input: ['text', 'image'], output: ['text'] },
        limit: { context: 200000, output: 100000 },
        cost: { input: 15.0, output: 60.0 },
        knowledge: '2023-10',
        release_date: '2024-12-05',
        last_updated: '2024-12-05',
        open_weights: false,
      },
    },
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    api: 'https://api.anthropic.com',
    npm: '@anthropic-ai/sdk',
    doc: 'https://docs.anthropic.com',
    env: ['ANTHROPIC_API_KEY'],
    models: {
      'claude-3-5-sonnet-latest': {
        id: 'claude-3-5-sonnet-latest',
        name: 'Claude 3.5 Sonnet',
        family: 'claude-3.5-sonnet',
        reasoning: false,
        tool_call: true,
        temperature: true,
        attachment: true,
        modalities: { input: ['text', 'image'], output: ['text'] },
        limit: { context: 200000, output: 8192 },
        cost: { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
        knowledge: '2024-04',
        release_date: '2024-06-20',
        last_updated: '2024-10-22',
        open_weights: false,
      },
      'claude-3-5-haiku-latest': {
        id: 'claude-3-5-haiku-latest',
        name: 'Claude 3.5 Haiku',
        family: 'claude-3.5-haiku',
        reasoning: false,
        tool_call: true,
        temperature: true,
        attachment: true,
        modalities: { input: ['text'], output: ['text'] },
        limit: { context: 200000, output: 8192 },
        cost: { input: 0.8, output: 4.0 },
        knowledge: '2024-07',
        release_date: '2024-11-04',
        last_updated: '2024-11-04',
        open_weights: false,
      },
      'claude-3-opus-latest': {
        id: 'claude-3-opus-latest',
        name: 'Claude 3 Opus',
        family: 'claude-3-opus',
        reasoning: false,
        tool_call: true,
        temperature: true,
        attachment: true,
        modalities: { input: ['text', 'image'], output: ['text'] },
        limit: { context: 200000, output: 4096 },
        cost: { input: 15.0, output: 75.0, cache_read: 1.5, cache_write: 18.75 },
        knowledge: '2024-02',
        release_date: '2024-02-01',
        last_updated: '2024-04-01',
        open_weights: false,
      },
    },
  },
  {
    id: 'google',
    name: 'Google',
    api: 'https://generativelanguage.googleapis.com',
    npm: '@google/generative-ai',
    doc: 'https://ai.google.dev',
    env: ['GOOGLE_API_KEY'],
    models: {
      'gemini-2.0-flash': {
        id: 'gemini-2.0-flash',
        name: 'Gemini 2.0 Flash',
        family: 'gemini-2.0',
        reasoning: false,
        tool_call: true,
        temperature: true,
        attachment: true,
        modalities: { input: ['text', 'image', 'audio', 'video'], output: ['text'] },
        limit: { context: 1000000, output: 8192 },
        cost: { input: 0.1, output: 0.4 },
        knowledge: '2024-06',
        release_date: '2025-02-05',
        last_updated: '2025-02-05',
        open_weights: false,
      },
      'gemini-2.0-flash-thinking': {
        id: 'gemini-2.0-flash-thinking',
        name: 'Gemini 2.0 Flash Thinking',
        family: 'gemini-2.0',
        reasoning: true,
        tool_call: true,
        temperature: true,
        attachment: true,
        modalities: { input: ['text', 'image'], output: ['text'] },
        limit: { context: 1000000, output: 8192 },
        cost: { input: 0.1, output: 0.4 },
        knowledge: '2024-06',
        release_date: '2025-02-05',
        last_updated: '2025-02-05',
        open_weights: false,
      },
      'gemini-1.5-pro': {
        id: 'gemini-1.5-pro',
        name: 'Gemini 1.5 Pro',
        family: 'gemini-1.5',
        reasoning: false,
        tool_call: true,
        temperature: true,
        attachment: true,
        modalities: { input: ['text', 'image', 'audio', 'video'], output: ['text'] },
        limit: { context: 2000000, output: 8192 },
        cost: { input: 1.25, output: 5.0 },
        knowledge: '2024-05',
        release_date: '2024-05-24',
        last_updated: '2024-09-01',
        open_weights: false,
      },
    },
  },
  {
    id: 'xai',
    name: 'xAI',
    api: 'https://api.x.ai',
    npm: 'openai',
    doc: 'https://docs.x.ai',
    env: ['XAI_API_KEY'],
    models: {
      'grok-2': {
        id: 'grok-2',
        name: 'Grok 2',
        family: 'grok-2',
        reasoning: false,
        tool_call: true,
        temperature: true,
        attachment: true,
        modalities: { input: ['text'], output: ['text'] },
        limit: { context: 131072, output: 8192 },
        cost: { input: 2.0, output: 10.0 },
        knowledge: '2024-07',
        release_date: '2024-08-13',
        last_updated: '2024-08-13',
        open_weights: false,
      },
      'grok-2-vision': {
        id: 'grok-2-vision',
        name: 'Grok 2 Vision',
        family: 'grok-2',
        reasoning: false,
        tool_call: true,
        temperature: true,
        attachment: true,
        modalities: { input: ['text', 'image'], output: ['text'] },
        limit: { context: 32768, output: 8192 },
        cost: { input: 2.0, output: 10.0 },
        knowledge: '2024-07',
        release_date: '2024-08-13',
        last_updated: '2024-08-13',
        open_weights: false,
      },
    },
  },
  {
    id: 'alibaba',
    name: 'Alibaba Cloud',
    api: 'https://dashscope.aliyuncs.com/api/v1',
    npm: 'openai',
    doc: 'https://help.aliyun.com/dashscope',
    env: ['DASHSCOPE_API_KEY'],
    models: {
      'qwen-max': {
        id: 'qwen-max',
        name: 'Qwen Max',
        family: 'qwen',
        reasoning: true,
        tool_call: true,
        temperature: true,
        attachment: true,
        modalities: { input: ['text', 'image'], output: ['text'] },
        limit: { context: 32000, output: 8192 },
        cost: { input: 0.5, output: 2.0 },
        knowledge: '2024-08',
        release_date: '2024-09-01',
        last_updated: '2024-09-01',
        open_weights: false,
      },
      'qwen-coder-plus': {
        id: 'qwen-coder-plus',
        name: 'Qwen Coder Plus',
        family: 'qwen-coder',
        reasoning: false,
        tool_call: true,
        temperature: true,
        attachment: true,
        modalities: { input: ['text'], output: ['text'] },
        limit: { context: 131072, output: 8192 },
        cost: { input: 0.2, output: 0.6 },
        knowledge: '2024-08',
        release_date: '2024-11-01',
        last_updated: '2024-11-01',
        open_weights: false,
      },
      'qwen-vl-max': {
        id: 'qwen-vl-max',
        name: 'Qwen VL Max',
        family: 'qwen-vl',
        reasoning: false,
        tool_call: true,
        temperature: true,
        attachment: true,
        modalities: { input: ['text', 'image'], output: ['text'] },
        limit: { context: 32000, output: 8192 },
        cost: { input: 0.4, output: 1.2 },
        knowledge: '2024-08',
        release_date: '2024-09-01',
        last_updated: '2024-09-01',
        open_weights: false,
      },
    },
  },
  {
    id: 'moonshotai',
    name: 'Moonshot AI',
    api: 'https://api.moonshot.cn/v1',
    npm: 'openai',
    doc: 'https://platform.moonshot.cn',
    env: ['MOONSHOT_API_KEY'],
    models: {
      'kimi-k2': {
        id: 'kimi-k2',
        name: 'Kimi K2',
        family: 'kimi',
        reasoning: true,
        tool_call: true,
        temperature: true,
        attachment: true,
        modalities: { input: ['text', 'image'], output: ['text'] },
        limit: { context: 256000, output: 8192 },
        cost: { input: 0.3, output: 0.9 },
        knowledge: '2024-12',
        release_date: '2025-02-15',
        last_updated: '2025-02-15',
        open_weights: false,
      },
      'kimi-latest': {
        id: 'kimi-latest',
        name: 'Kimi Latest',
        family: 'kimi',
        reasoning: false,
        tool_call: true,
        temperature: true,
        attachment: true,
        modalities: { input: ['text'], output: ['text'] },
        limit: { context: 200000, output: 8192 },
        cost: { input: 0.2, output: 0.6 },
        knowledge: '2024-08',
        release_date: '2024-10-01',
        last_updated: '2024-10-01',
        open_weights: false,
      },
    },
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    api: 'https://api.deepseek.com',
    npm: 'openai',
    doc: 'https://platform.deepseek.com',
    env: ['DEEPSEEK_API_KEY'],
    models: {
      'deepseek-chat': {
        id: 'deepseek-chat',
        name: 'DeepSeek V3',
        family: 'deepseek-v3',
        reasoning: false,
        tool_call: true,
        temperature: true,
        attachment: true,
        modalities: { input: ['text'], output: ['text'] },
        limit: { context: 64000, output: 8192 },
        cost: { input: 0.1, output: 0.3 },
        knowledge: '2024-06',
        release_date: '2024-12-26',
        last_updated: '2024-12-26',
        open_weights: true,
      },
      'deepseek-reasoner': {
        id: 'deepseek-reasoner',
        name: 'DeepSeek R1',
        family: 'deepseek-r1',
        reasoning: true,
        tool_call: true,
        temperature: true,
        attachment: true,
        modalities: { input: ['text'], output: ['text'] },
        limit: { context: 64000, output: 8192 },
        cost: { input: 0.5, output: 2.0 },
        knowledge: '2024-06',
        release_date: '2025-01-20',
        last_updated: '2025-01-20',
        open_weights: true,
      },
    },
  },
  {
    id: 'groq',
    name: 'Groq',
    api: 'https://api.groq.com/openai/v1',
    npm: 'openai',
    doc: 'https://console.groq.com/docs',
    env: ['GROQ_API_KEY'],
    models: {
      'llama-3.3-70b-versatile': {
        id: 'llama-3.3-70b-versatile',
        name: 'Llama 3.3 70B',
        family: 'llama-3.3',
        reasoning: false,
        tool_call: true,
        temperature: true,
        attachment: true,
        modalities: { input: ['text'], output: ['text'] },
        limit: { context: 128000, output: 32768 },
        cost: { input: 0.59, output: 0.79 },
        knowledge: '2024-06',
        release_date: '2024-12-01',
        last_updated: '2024-12-01',
        open_weights: true,
      },
      'deepseek-r1-distill-llama-70b': {
        id: 'deepseek-r1-distill-llama-70b',
        name: 'DeepSeek R1 Distill Llama 70B',
        family: 'deepseek-r1-distill',
        reasoning: true,
        tool_call: true,
        temperature: true,
        attachment: true,
        modalities: { input: ['text'], output: ['text'] },
        limit: { context: 128000, output: 32768 },
        cost: { input: 0.75, output: 0.99 },
        knowledge: '2024-06',
        release_date: '2025-01-20',
        last_updated: '2025-01-20',
        open_weights: true,
      },
    },
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    api: 'https://api.minimax.chat/v1',
    npm: 'openai',
    doc: 'https://platform.minimaxi.com',
    env: ['MINIMAX_API_KEY'],
    models: {
      'abab6.5s-chat': {
        id: 'abab6.5s-chat',
        name: 'ABAB 6.5s',
        family: 'abab',
        reasoning: false,
        tool_call: true,
        temperature: true,
        attachment: true,
        modalities: { input: ['text'], output: ['text'] },
        limit: { context: 8000, output: 4096 },
        cost: { input: 0.15, output: 0.6 },
        knowledge: '2024-06',
        release_date: '2024-05-01',
        last_updated: '2024-05-01',
        open_weights: false,
      },
    },
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    api: 'https://openrouter.ai/api/v1',
    npm: 'openai',
    doc: 'https://openrouter.ai/docs',
    env: ['OPENROUTER_API_KEY'],
    models: {
      'openrouter/auto': {
        id: 'openrouter/auto',
        name: 'OpenRouter Auto',
        family: 'auto',
        reasoning: false,
        tool_call: true,
        temperature: true,
        attachment: true,
        modalities: { input: ['text'], output: ['text'] },
        limit: { context: 128000, output: 8192 },
        cost: { input: 0.0, output: 0.0 },
        knowledge: '2024-06',
        release_date: '2024-01-01',
        last_updated: '2024-01-01',
        open_weights: false,
      },
    },
  },
  {
    id: 'ollama',
    name: 'Ollama',
    api: 'http://127.0.0.1:11434/v1',
    npm: 'ollama',
    doc: 'https://ollama.com',
    env: [],
    models: {
      'llama3.3': {
        id: 'llama3.3',
        name: 'Llama 3.3',
        family: 'llama',
        reasoning: false,
        tool_call: true,
        temperature: true,
        attachment: true,
        modalities: { input: ['text'], output: ['text'] },
        limit: { context: 128000, output: 8192 },
        cost: { input: 0, output: 0 },
        knowledge: '2024-06',
        release_date: '2024-12-01',
        last_updated: '2024-12-01',
        open_weights: true,
      },
    },
  },
];

/**
 * Built-in data metadata
 */
export const BUILT_IN_METADATA = {
  version: '1.0.0',
  lastUpdated: '2026-02-26',
  totalProviders: BUILT_IN_PROVIDERS.length,
  totalModels: BUILT_IN_PROVIDERS.reduce((sum, p) => sum + Object.keys(p.models).length, 0),
  source: 'https://models.dev',
};
